### ISSUE TITLE
Error, please fix. Greta plugin

### ISSUE THREAD

**Issue by ThePenguinCDB** [Clarence2810/TagMessages#4]
24
[30]                    Main::getInstance()->getScheduler()->cancelTask($this->getTaskId());
25
[31]                    unset(Main::$stop[array_search($this->player->getName(), Main::$stop)]);
26
[32]                }
27
[33]            }
28
[34]            if($this->show <= 1){
29
[35]                unset(Main::$new[array_search($this->player->getName(), Main::$new)]);
30
[36]                unset(Main::$first[array_search($this->player->getName(), Main::$first)]);
31
[37]                Main::getInstance()->getScheduler()->cancelTask($this->getTaskId());
32
​
33
Backtrace:
34
#0 pmsrc/src/pocketmine/scheduler/TaskHandler(137): Clarence2810\tagmessages\TagTask->onRun(integer 596)
35
#1 pmsrc/src/pocketmine/scheduler/TaskScheduler(179): pocketmine\scheduler\TaskHandler->run(integer 596)
36
#2 pmsrc/src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 596)
37
#3 pmsrc/src/pocketmine/Server(2390): pocketmine\plugin\PluginManager->tickSchedulers(integer 596)
38
#4 pmsrc/src/pocketmine/Server(2153): pocketmine\Server->tick()
39
#5 pmsrc/src/pocketmine/Server(1993): pocketmine\Server->tickProcessor()
40
#6 pmsrc/src/pocketmine/Server(1587): pocketmine\Server->start()
41
#7 pmsrc/src/pocketmine/PocketMine(286): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
42
#8 pmsrc/src/pocketmine/PocketMine(316): pocketmine\server()
43
#9 pmsrc(11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
44
​
45
PocketMine-MP version: 3.17.4 [Protocol 422]
46
Git commit: 2e9117d102b1b5c734292ff0bcdcbc49e3748a89
47
uname -a: Linux 3f8dd071-11f6-4693-9f52-32153fc2a39b 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64
48
PHP Version: 7.3.23
49
Zend version: 3.3.23
50
OS : Linux, linux
51
Composer libraries: 
52
- adhocore/json-comment 0.1.0@8448076039389f558f39ad0553aab87db3f81614
53
- daverandom/callback-validator unknown@unknown
54
- pocketmine/binaryutils 0.1.13@0abee38d4e2861621f262c79a2a3d699d8a697f4
55
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
56
- pocketmine/classloader 0.1.2@9757928424652393b178a3760073113aa7c9911b
57
- pocketmine/log 0.2.1@830b44a2cf96ef703c550abe64302f230231ca49
58
- pocketmine/log-pthreads 0.1.3@e477ecf6ec214fdd4415ea1da3fdd9d73bf699ea
59
- pocketmine/math 0.2.6@43057cb8c179a9859677b496a788db922fd5cfc3
60
- pocketmine/nbt 0.2.16@be6d54a8a314967d938b501eee49d4641e2ab07d
61
- pocketmine/pocketmine-mp 3.17.4@2e9117d102b1b5c734292ff0bcdcbc49e3748a89
62
- pocketmine/raklib 0.12.10@48e70551cca6f2409115d3468bed94c2edd08f31
63
- pocketmine/snooze 0.1.4@382ab149f01ecca0a57f999ff5d7fc9e271c3268
64
- pocketmine/spl 0.4.2@6b08b7cf8c4afa17139c9a1b3bf1b408531de161
65
​

**Comment by Clarence2810** [comment]
Install the new version of TagMessages.

Same Issue: #2
Link:  https://poggit.pmmp.io/p/TagMessages/1.1.1
